# This is the main maven workflow for SWT.

# You can run this locally to test changes with the act command https://nektosact.com/
# For example, to run all GTK4 tests:
#   act -j build-linux --matrix java:21 --matrix gtk:gtk4 --artifact-server-path $PWD/.artifacts
# You may need to download runners on first run, act will ask but if you
# want the big runner there is no progress as it downloads, so you can pull it with
# docker directly:
#   docker pull catthehacker/ubuntu:full-latest

name: SWT Matrix Build
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
  push:
    branches: [ skia_canvas ]
  pull_request:
    branches: [ skia_canvas ]
    types: [opened, reopened, synchronize, labeled]

env:
  SWT_GTK4: "${{ contains(github.event.pull_request.labels.*.name, 'gtk4') && '1' || '0' }}"

jobs:
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
 Detect changed paths
    runs-on: ubuntu-latest
    outputs:
      # Lint w  build:
ch64]
    uses: ./.github/workflows/build.yml
    with:
      runner: ${{ matrix.arch == 'x86_64' && 'macos-15-intel' || 'macos-latest' }}
      java: ${{ matrix.java }}
      native: ${{ matrix.arch == 'x86_64' && 'cocoa.macosx.x86_64' || 'cocoa.macosx.aarch64' }}
      performance: ${{ contains(github.event.pull_request.labels.*.name, 'performance') }}
      runtodotests: ${{ contains(github.event.pull_request.labels.*.name, 'runtodotests') }}